# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: hmp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.3.5
  - bracken=2.5
  - cd-hit=4.8.1
  - checkm-genome=1.1.2
  - fastp=0.20.0
  - fastqc=0.11.8
  - gtdbtk=1.0.1
  - kraken2=2.0.8_beta
  - megahit=1.2.9
  - metabat2=2.15
  - multiqc=1.8
  - plass=2.c7e35
  - prokka=1.14.5
  - quast=5.0.2
  - salmon=1.1.0
  - samtools=1.9
  - trinity=2.9.1